class ProcessingError(Exception):
    pass


class Continue(Exception):
    pass
